apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: bullmq-worker-scaler
  namespace: orch-109920256
spec:
  scaleTargetRef:
    name: bullmq-worker-deployment
  minReplicaCount: 0
  maxReplicaCount: 90
  pollingInterval: 5 # check every 15s
  cooldownPeriod: 10 # time to wait after last trigger before scaling down
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 30 # scale down from max to min within 30s of an empty queue
          policies:
            - type: Percent
              value: 100
              periodSeconds: 10 # limit no. pods deleted within 10s (traffic control)
  triggers:
    - type: redis
      metadata:
        address: redis-service.orch-109920256.svc.cluster.local:6379
        listName: bull:jobQueue:wait
        listLength: "2" # keep it low for demo purposes
