apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: orch-109920256
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis:7.4
          ports:
            containerPort: 6379
