apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-server-deployment
  namespace: orch-109920256
  labels:
    app: main-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-server
  template:
    metadata:
      labels:
        app: main-server
    spec:
      containers:
        - name: main-server-container
          image: zjlianlee/clo835-project-main-server:latest
          ports:
            - containerPort: 3000
          env:
            - name: MAIN_SERVER_PORT
              value: "3000"
            - name: ORCHESTRATOR_URL
              value: "http://task-orchestrator-service:3001"
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
            - name: ADMIN_SECRET
              value: ""
